spring:
  datasource:
    url: jdbc:mysql://:3306/jiandan_house?characterEncoding=utf-8&useSSL=false
    username: 
    password: 
  jpa:
      show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG